server:
  port: 5000

deepl:
  api:
    key:
    url: https://api-free.deepl.com/v2/translate

gemini:
  api:
    key:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update